### ISSUE TITLE
Cannot Launch Files With Spaces

### ISSUE THREAD

**Issue by memtech3** [marimo-team/vscode-marimo#16]
Marimo VSCode extension will not launch files with spaces in their filenames.

Solution: Add quotes around file path before passing to terminal

Command Prompt output: 
`marimo -d run Examples\Normal Stress.py --port=2718 --headless`
`Error: Got unexpected extra argument (Stress.py)`

Marimo Info:
Version: v0.1.11

VSCode Info:
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by memtech3** [comment]
@mscolnick wow that was quick! New bug noted: on windows the filename has to be surrounded by "double quotes", 'single quotes' gives me the error `Error: Invalid NAME - '.\HW3\Q2.py' is not a Python file`

**Comment by mscolnick** [comment]
just released `v0.1.13.` with the fix

**Comment by memtech3** [comment]
Thanks, it works now! Impressively quick turn around!

**Comment by memtech3** [comment]
Not sure if this is worth the mental overhead right now but I've found a library to do CI testing for VSCode extensions. 
You could have GitHub actions run the extension in windows mac and linux runners to catch this kind of issue
https://github.com/redhat-developer/vscode-extension-tester

**Comment by mscolnick** [comment]
@memtech3 thank you for the pointer - i hadn't seen this before. I'll look into it if the extension starts to grow in scope / needs e2e testing
