### ISSUE TITLE
Open in embedded/external browser does not provide access token

### ISSUE THREAD

**Issue by niowniow** [marimo-team/vscode-marimo#25]
When I try out a simple example, I cannot get it to run in the embedded or external browser when launching it from VSCode.

It just shows this page
![image](https://github.com/marimo-team/vscode-marimo/assets/5802846/cc4244a3-8524-4ab7-9a09-79cc673ebb92)

It seems that the access token is not provided by this VSCode extension. 

If I click on marimo -> Show Terminal. I see the following and the contained link works
```
marimo edit test.py --port=2723 --headless
        Edit test.py in your browser 📝
        URL: http://localhost:2723?access_token=...
```
        
I can also start the same file from a regular terminal successfully using

```
marimo edit test.py
```

**Comment by mscolnick** [comment]
We just added auth to `marimo cli` by default. I can make this configurable (and likely off by default since most vscode development is local)

**Comment by mscolnick** [comment]
@niowniow I just released `v0.2.2`. Can you upgrade and give it a try? 

I also added `Export notebooks as: html, markdown, or scripts.`

**Comment by niowniow** [comment]
That was fast. I can confirm that it works know. Thank you!
Also export works. I expected some form of confirmation, though, like some indicator that the export was successful.

**Comment by mscolnick** [comment]
@niowniow there is a toast in the bottom right when the export is finished
