### ISSUE TITLE
Add to OpenVSX

### ISSUE THREAD

**Issue by roaldarbol** [marimo-team/vscode-marimo#26]
Looking forward to trying the extension!

It would be great to be able to install the extension in derivatives of VS Code such as VSCodium without having to download the `vsix` file. To enable that, you can upload the extension to OpenVSX, the open extension registry. There's a guide on how to do that [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by mscolnick** [comment]
will do this today!

**Comment by mscolnick** [comment]
It has be published: https://open-vsx.org/extension/marimo-team/vscode-marimo, and extension verification in progress (https://github.com/EclipseFdn/open-vsx.org/issues/2653)
