### ISSUE TITLE
0.3.0 error: Commands not found

### ISSUE THREAD

**Issue by dmadisetti** [marimo-team/vscode-marimo#30]
```text
Error running command vscode-marimo.newMarimoFile: command 'vscode-marimo.newMarimoFile' not found. This is likely caused by the extension that contributes vscode-marimo.newMarimoFile.
```

Not super well versed in VSCode, but I got it working before going over to the pre-release. Refresh and other end points also seem broken

Might try running from source instead, is there a dev doc? Interested in to checkout the integration.

---

Edit: I tried disabling and enabling, but I think things are now worse since I'm not getting the little marimo specific items in the upper right.

**Comment by dmadisetti** [comment]
? I think you must have pushed a change, no problem now and can't replicate

**Comment by mscolnick** [comment]
Yea I published a bad build
