### ISSUE TITLE
Marimo and Pixi

### ISSUE THREAD

**Issue by claudiushaag** [marimo-team/vscode-marimo#37]
Marimo in the embedded browser is super cool!

For me, there are currently two Problems with how the marimo-extension slows down my user experience significantly.

First, the marimo extension tries to list all marimo apps embedded within the installed pixi-environments of the respective pixi project.
This means, that on my machine, the "Application" Column of the extension stays empty, and I'm not able to select the notebook I would like to work on until the extension has found all marimo notebooks in the pixi-environment. During this time, almost all ressources of my laptop are allocated for vs code.

I don't see a apparent reason for listing all notebooks. I would much prefer only the ones in the local workspace. I think it would be cool, if one could at least access a "exclude" setting, where such behaviour could be altered.

Additionally, I think, this search-process induces another problem: With activated marimo-extension, Pylance starts analyzing the files in the pixi-environment, which it does not do when the marimo-extension is deactivated. This leads to another surge of files apparently being screened.

Setting:
- Windows 11 Pro, 10.0.22631
- VS Code: 
  - Version: 1.92.0 (user setup)
  - Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
  - Date: 2024-07-31T23:26:45.634Z
  - Electron: 30.1.2
  - ElectronBuildId: 9870757
  - Chromium: 124.0.6367.243
  - Node.js: 20.14.0
  - V8: 12.4.254.20-electron.0
  - OS: Windows_NT x64 10.0.22631
- Marimo-Extension: v0.4.2
- Pylance: v2024.8.1

**Comment by claudiushaag** [comment]
So, as a fun evening event, I took my first steps with vs code extensions, node.js and all of that ^^

So what I found: Critical are the following [lines](https://github.com/marimo-team/vscode-marimo/blob/e17a925d453886b78c11c9bdc2609ebe8e428775/src/explorer/explorer.ts#L84-L88)
The second argument controls the exclude globs. So here, adding ``**/marimo/**`` solves my problem of the extension listing the tutorials and especially, reading all the files in the subsequent [lines](https://github.com/marimo-team/vscode-marimo/blob/e17a925d453886b78c11c9bdc2609ebe8e428775/src/explorer/explorer.ts#L92-L106) and checking for the ``app = marimo.App(`` line.

But I'm wondering if there is any reason to argue against ommitting all folders starting with a dot? ``**/.*/**`` or ``**/.pixi/**`` would be certainly possible as well, so ommitting all files of all hidden folders or just the pixi environment.

What is your opinion on that? I can draft a PR for that.

**Comment by mscolnick** [comment]
I appreciate you debugging this. 

Ignoring all `**/.*/**` or `**/.pixi/**` would be great. thank you for offering to create the PR
