### ISSUE TITLE
Add option to run with --sandbox

### ISSUE THREAD

**Issue by gabrielgrant** [marimo-team/vscode-marimo#53]
AFAICT there isn't a way to do this right now? Result is that I get the missing packages error when running notebooks created using a `--sandbox` server:

![Image](https://github.com/user-attachments/assets/2449d3fe-247d-4ba6-95b9-8cb3813c272e)

Would be great if this happened (or at least prompted) automatically (which seems to have been introduced in https://github.com/marimo-team/marimo/issues/2414 ) but not sure how that would work with the default of not even showing the terminal marimo is running in

**Comment by mscolnick** [comment]
We start one edit server for all notebooks started from vscode, so we would need to first add this feature to marimo core: [make sandbox compatible with edit server (multiple notebooks)](https://github.com/marimo-team/marimo/issues/2598).

**Comment by gabrielgrant** [comment]
As I [mentioned on that issue](https://github.com/marimo-team/marimo/issues/2598#issuecomment-2455458558) it does seem like `marimo edit --sandbox` is at least partially working today. Would you be open to having a setting (default off) that would allow running in the same way? IIUC that would at least allow working with my existing sandboxed notebooks so long as there aren't package version conflicts between those currently running, yes?

**Comment by gabrielgrant** [comment]
Thanks for getting to this! Was hoping i might be able to get it done, but had a very full plate last week
