### ISSUE TITLE
Marimo installation not detected (`Error: Command Failed: .... : No such file or directory`)

### ISSUE THREAD

**Issue by AVDiv** [marimo-team/vscode-marimo#55]
# Bug Description

The Marimo server fails after startup (Actually when it's checking for the marimo installation).

![Image](https://github.com/user-attachments/assets/51d4019e-f8fb-47f0-8fa0-4affb284577c)

The issue is with the interpreter path in the command, it does not use the quotes (or backslash) to escape the blank character in the interpreter path. I know I can set the interpreter path correctly in the extension settings, but I doesn't feel like a real fix for that.

Btw, I really appreciate this tool, thank you for your service 🫡.

# Enviroment

**Python version:** 3.12.7
**Marimo version:** 0.9.19

**OS:** Linux (Arch)
**CPU Architecture:** x86_64
**Shell:** Fish

**Comment by mscolnick** [comment]
Fixed by https://github.com/marimo-team/vscode-marimo/pull/56 and released in 0.4.7
